dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t dricevans/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dricevans/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-750235574254"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
